=== dimitar-radenkov/XML-basic/students.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="sex" type="xs:string" />
              <xs:element name="birthDate" type="xs:string" />
              <xs:element name="phone" type="xs:unsignedInt" />
              <xs:element name="email" type="xs:string" />
              <xs:element name="course" type="xs:string" />
              <xs:element name="specialty" type="xs:string" />
              <xs:element name="facultyNumber" type="xs:unsignedInt" />
              <xs:element maxOccurs="unbounded" name="exams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="tutor" type="xs:string" />
                    <xs:element name="score" type="xs:unsignedByte" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="enrollment">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="date" type="xs:dateTime" />
                    <xs:element name="examScore" type="xs:unsignedByte" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element maxOccurs="1" name="endorsements">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Discipline" type="xs:string" />
                    <xs:element name="TeacherName" type="xs:string" />
                    <xs:element name="signature" type="xs:boolean" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dimitar-radenkov/XML-basic/students.xml
<?xml version="1.0" encoding="utf-8" ?>
<students xmlns="urn:students"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="students.xsd">
           <!--xsi:schemaLocation="urn:students students.xsd"-->
  <student>
    <name>Anton</name>
    <sex>m</sex>
    <birthDate>1/2000</birthDate>
    <phone> 0888888888</phone>
    <email>rrrr@abv.bg</email>
    <course>css</course>
    <specialty>Everything</specialty>
    <facultyNumber>900233</facultyNumber>
    <exams>
      <name>Deleting</name>
      <tutor>Ivanov</tutor>
      <score>2</score>
    </exams>
    <exams>
      <name>Shining</name>
      <tutor>Petko</tutor>
      <score>2</score>
    </exams>
  </student>
  <student>
    <name>Anton</name>
    <sex>m</sex>
    <birthDate>1/2000</birthDate>
    <phone> 0888888888</phone>
    <email>rrrr@abv.bg</email>
    <course>css</course>
    <specialty>Everything</specialty>
    <facultyNumber>900233</facultyNumber>
    <exams>
      <name>Shining</name>
      <tutor>Petko</tutor>
      <score>2</score>
    </exams>
  </student>
</students>
